### ISSUE TITLE
The DataStores/Repository/Sql files is missing

### ISSUE THREAD

**Issue by nohros** [Shuttle/Shuttle.Esb.Management#6]
The Shuttle.Management.Shell project references the following missing files:
- DataStore.sql
- DataStoreColumns.cs
- DataStoreMapper.cs
- DataStoreTableAccess.cs
- SqlDataStoreRepository.cs

**Comment by eben-roux** [comment]
I'm terribly sorry about this :(

I only noticed this issue now --- I don't know why I didn't get an e-mail (or I missed it).

Anyway.  The files have been added.  I had `sql` in my `.gitignore` file.
